// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: orange/config/admin/v1/admin.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dio/orange/api/orange/config/admin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConfigAdminServiceName is the fully-qualified name of the ConfigAdminService service.
	ConfigAdminServiceName = "orange.config.admin.v1.ConfigAdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConfigAdminServicePublishSnapshotProcedure is the fully-qualified name of the
	// ConfigAdminService's PublishSnapshot RPC.
	ConfigAdminServicePublishSnapshotProcedure = "/orange.config.admin.v1.ConfigAdminService/PublishSnapshot"
)

// ConfigAdminServiceClient is a client for the orange.config.admin.v1.ConfigAdminService service.
type ConfigAdminServiceClient interface {
	// PublishSnapshot stores a new compiled config snapshot for later polling
	// through SnapshotService.Fetch.
	PublishSnapshot(context.Context, *connect.Request[v1.PublishSnapshotRequest]) (*connect.Response[v1.PublishSnapshotResponse], error)
}

// NewConfigAdminServiceClient constructs a client for the orange.config.admin.v1.ConfigAdminService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConfigAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConfigAdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	configAdminServiceMethods := v1.File_orange_config_admin_v1_admin_proto.Services().ByName("ConfigAdminService").Methods()
	return &configAdminServiceClient{
		publishSnapshot: connect.NewClient[v1.PublishSnapshotRequest, v1.PublishSnapshotResponse](
			httpClient,
			baseURL+ConfigAdminServicePublishSnapshotProcedure,
			connect.WithSchema(configAdminServiceMethods.ByName("PublishSnapshot")),
			connect.WithClientOptions(opts...),
		),
	}
}

// configAdminServiceClient implements ConfigAdminServiceClient.
type configAdminServiceClient struct {
	publishSnapshot *connect.Client[v1.PublishSnapshotRequest, v1.PublishSnapshotResponse]
}

// PublishSnapshot calls orange.config.admin.v1.ConfigAdminService.PublishSnapshot.
func (c *configAdminServiceClient) PublishSnapshot(ctx context.Context, req *connect.Request[v1.PublishSnapshotRequest]) (*connect.Response[v1.PublishSnapshotResponse], error) {
	return c.publishSnapshot.CallUnary(ctx, req)
}

// ConfigAdminServiceHandler is an implementation of the orange.config.admin.v1.ConfigAdminService
// service.
type ConfigAdminServiceHandler interface {
	// PublishSnapshot stores a new compiled config snapshot for later polling
	// through SnapshotService.Fetch.
	PublishSnapshot(context.Context, *connect.Request[v1.PublishSnapshotRequest]) (*connect.Response[v1.PublishSnapshotResponse], error)
}

// NewConfigAdminServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConfigAdminServiceHandler(svc ConfigAdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	configAdminServiceMethods := v1.File_orange_config_admin_v1_admin_proto.Services().ByName("ConfigAdminService").Methods()
	configAdminServicePublishSnapshotHandler := connect.NewUnaryHandler(
		ConfigAdminServicePublishSnapshotProcedure,
		svc.PublishSnapshot,
		connect.WithSchema(configAdminServiceMethods.ByName("PublishSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	return "/orange.config.admin.v1.ConfigAdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConfigAdminServicePublishSnapshotProcedure:
			configAdminServicePublishSnapshotHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConfigAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConfigAdminServiceHandler struct{}

func (UnimplementedConfigAdminServiceHandler) PublishSnapshot(context.Context, *connect.Request[v1.PublishSnapshotRequest]) (*connect.Response[v1.PublishSnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.config.admin.v1.ConfigAdminService.PublishSnapshot is not implemented"))
}
