// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: orange/config/v1/service.proto

package configv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dio/orange/api/orange/config/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SnapshotServiceName is the fully-qualified name of the SnapshotService service.
	SnapshotServiceName = "orange.config.v1.SnapshotService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SnapshotServiceFetchMappedSplitMapProcedure is the fully-qualified name of the SnapshotService's
	// FetchMappedSplitMap RPC.
	SnapshotServiceFetchMappedSplitMapProcedure = "/orange.config.v1.SnapshotService/FetchMappedSplitMap"
	// SnapshotServiceFetchMappedSplitBundleProcedure is the fully-qualified name of the
	// SnapshotService's FetchMappedSplitBundle RPC.
	SnapshotServiceFetchMappedSplitBundleProcedure = "/orange.config.v1.SnapshotService/FetchMappedSplitBundle"
)

// SnapshotServiceClient is a client for the orange.config.v1.SnapshotService service.
type SnapshotServiceClient interface {
	// FetchMappedSplitMap returns the typed mapped-split SoTW map for the
	// authenticated lane. Component bundles referenced by the map are fetched
	// separately through FetchMappedSplitBundle.
	FetchMappedSplitMap(context.Context, *connect.Request[v1.FetchMappedSplitMapRequest]) (*connect.Response[v1.FetchMappedSplitMapResponse], error)
	// FetchMappedSplitBundle returns one component bundle resource referenced by
	// the typed mapped-split map for the authenticated lane.
	FetchMappedSplitBundle(context.Context, *connect.Request[v1.FetchMappedSplitBundleRequest]) (*connect.Response[v1.FetchMappedSplitBundleResponse], error)
}

// NewSnapshotServiceClient constructs a client for the orange.config.v1.SnapshotService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSnapshotServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SnapshotServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	snapshotServiceMethods := v1.File_orange_config_v1_service_proto.Services().ByName("SnapshotService").Methods()
	return &snapshotServiceClient{
		fetchMappedSplitMap: connect.NewClient[v1.FetchMappedSplitMapRequest, v1.FetchMappedSplitMapResponse](
			httpClient,
			baseURL+SnapshotServiceFetchMappedSplitMapProcedure,
			connect.WithSchema(snapshotServiceMethods.ByName("FetchMappedSplitMap")),
			connect.WithClientOptions(opts...),
		),
		fetchMappedSplitBundle: connect.NewClient[v1.FetchMappedSplitBundleRequest, v1.FetchMappedSplitBundleResponse](
			httpClient,
			baseURL+SnapshotServiceFetchMappedSplitBundleProcedure,
			connect.WithSchema(snapshotServiceMethods.ByName("FetchMappedSplitBundle")),
			connect.WithClientOptions(opts...),
		),
	}
}

// snapshotServiceClient implements SnapshotServiceClient.
type snapshotServiceClient struct {
	fetchMappedSplitMap    *connect.Client[v1.FetchMappedSplitMapRequest, v1.FetchMappedSplitMapResponse]
	fetchMappedSplitBundle *connect.Client[v1.FetchMappedSplitBundleRequest, v1.FetchMappedSplitBundleResponse]
}

// FetchMappedSplitMap calls orange.config.v1.SnapshotService.FetchMappedSplitMap.
func (c *snapshotServiceClient) FetchMappedSplitMap(ctx context.Context, req *connect.Request[v1.FetchMappedSplitMapRequest]) (*connect.Response[v1.FetchMappedSplitMapResponse], error) {
	return c.fetchMappedSplitMap.CallUnary(ctx, req)
}

// FetchMappedSplitBundle calls orange.config.v1.SnapshotService.FetchMappedSplitBundle.
func (c *snapshotServiceClient) FetchMappedSplitBundle(ctx context.Context, req *connect.Request[v1.FetchMappedSplitBundleRequest]) (*connect.Response[v1.FetchMappedSplitBundleResponse], error) {
	return c.fetchMappedSplitBundle.CallUnary(ctx, req)
}

// SnapshotServiceHandler is an implementation of the orange.config.v1.SnapshotService service.
type SnapshotServiceHandler interface {
	// FetchMappedSplitMap returns the typed mapped-split SoTW map for the
	// authenticated lane. Component bundles referenced by the map are fetched
	// separately through FetchMappedSplitBundle.
	FetchMappedSplitMap(context.Context, *connect.Request[v1.FetchMappedSplitMapRequest]) (*connect.Response[v1.FetchMappedSplitMapResponse], error)
	// FetchMappedSplitBundle returns one component bundle resource referenced by
	// the typed mapped-split map for the authenticated lane.
	FetchMappedSplitBundle(context.Context, *connect.Request[v1.FetchMappedSplitBundleRequest]) (*connect.Response[v1.FetchMappedSplitBundleResponse], error)
}

// NewSnapshotServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSnapshotServiceHandler(svc SnapshotServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	snapshotServiceMethods := v1.File_orange_config_v1_service_proto.Services().ByName("SnapshotService").Methods()
	snapshotServiceFetchMappedSplitMapHandler := connect.NewUnaryHandler(
		SnapshotServiceFetchMappedSplitMapProcedure,
		svc.FetchMappedSplitMap,
		connect.WithSchema(snapshotServiceMethods.ByName("FetchMappedSplitMap")),
		connect.WithHandlerOptions(opts...),
	)
	snapshotServiceFetchMappedSplitBundleHandler := connect.NewUnaryHandler(
		SnapshotServiceFetchMappedSplitBundleProcedure,
		svc.FetchMappedSplitBundle,
		connect.WithSchema(snapshotServiceMethods.ByName("FetchMappedSplitBundle")),
		connect.WithHandlerOptions(opts...),
	)
	return "/orange.config.v1.SnapshotService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SnapshotServiceFetchMappedSplitMapProcedure:
			snapshotServiceFetchMappedSplitMapHandler.ServeHTTP(w, r)
		case SnapshotServiceFetchMappedSplitBundleProcedure:
			snapshotServiceFetchMappedSplitBundleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSnapshotServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSnapshotServiceHandler struct{}

func (UnimplementedSnapshotServiceHandler) FetchMappedSplitMap(context.Context, *connect.Request[v1.FetchMappedSplitMapRequest]) (*connect.Response[v1.FetchMappedSplitMapResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.config.v1.SnapshotService.FetchMappedSplitMap is not implemented"))
}

func (UnimplementedSnapshotServiceHandler) FetchMappedSplitBundle(context.Context, *connect.Request[v1.FetchMappedSplitBundleRequest]) (*connect.Response[v1.FetchMappedSplitBundleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.config.v1.SnapshotService.FetchMappedSplitBundle is not implemented"))
}
