// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: orange/config/v1/service.proto

package configv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dio/orange/api/orange/config/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SnapshotServiceName is the fully-qualified name of the SnapshotService service.
	SnapshotServiceName = "orange.config.v1.SnapshotService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SnapshotServiceFetchProcedure is the fully-qualified name of the SnapshotService's Fetch RPC.
	SnapshotServiceFetchProcedure = "/orange.config.v1.SnapshotService/Fetch"
)

// SnapshotServiceClient is a client for the orange.config.v1.SnapshotService service.
type SnapshotServiceClient interface {
	// Fetch is the unary cold-start or reconnect path.
	// When last_version and last_checksum both still match the current snapshot,
	// the server returns Unchanged. Otherwise it returns the current envelope.
	Fetch(context.Context, *connect.Request[v1.FetchRequest]) (*connect.Response[v1.FetchResponse], error)
}

// NewSnapshotServiceClient constructs a client for the orange.config.v1.SnapshotService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSnapshotServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SnapshotServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	snapshotServiceMethods := v1.File_orange_config_v1_service_proto.Services().ByName("SnapshotService").Methods()
	return &snapshotServiceClient{
		fetch: connect.NewClient[v1.FetchRequest, v1.FetchResponse](
			httpClient,
			baseURL+SnapshotServiceFetchProcedure,
			connect.WithSchema(snapshotServiceMethods.ByName("Fetch")),
			connect.WithClientOptions(opts...),
		),
	}
}

// snapshotServiceClient implements SnapshotServiceClient.
type snapshotServiceClient struct {
	fetch *connect.Client[v1.FetchRequest, v1.FetchResponse]
}

// Fetch calls orange.config.v1.SnapshotService.Fetch.
func (c *snapshotServiceClient) Fetch(ctx context.Context, req *connect.Request[v1.FetchRequest]) (*connect.Response[v1.FetchResponse], error) {
	return c.fetch.CallUnary(ctx, req)
}

// SnapshotServiceHandler is an implementation of the orange.config.v1.SnapshotService service.
type SnapshotServiceHandler interface {
	// Fetch is the unary cold-start or reconnect path.
	// When last_version and last_checksum both still match the current snapshot,
	// the server returns Unchanged. Otherwise it returns the current envelope.
	Fetch(context.Context, *connect.Request[v1.FetchRequest]) (*connect.Response[v1.FetchResponse], error)
}

// NewSnapshotServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSnapshotServiceHandler(svc SnapshotServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	snapshotServiceMethods := v1.File_orange_config_v1_service_proto.Services().ByName("SnapshotService").Methods()
	snapshotServiceFetchHandler := connect.NewUnaryHandler(
		SnapshotServiceFetchProcedure,
		svc.Fetch,
		connect.WithSchema(snapshotServiceMethods.ByName("Fetch")),
		connect.WithHandlerOptions(opts...),
	)
	return "/orange.config.v1.SnapshotService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SnapshotServiceFetchProcedure:
			snapshotServiceFetchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSnapshotServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSnapshotServiceHandler struct{}

func (UnimplementedSnapshotServiceHandler) Fetch(context.Context, *connect.Request[v1.FetchRequest]) (*connect.Response[v1.FetchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.config.v1.SnapshotService.Fetch is not implemented"))
}
