// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orange/config/admin/v1/admin.proto

package adminv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/dio/orange/api/orange/auth/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSnapshotRequest) Reset() {
	*x = PublishSnapshotRequest{}
	mi := &file_orange_config_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSnapshotRequest) ProtoMessage() {}

func (x *PublishSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSnapshotRequest.ProtoReflect.Descriptor instead.
func (*PublishSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_orange_config_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

type PublishSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSnapshotResponse) Reset() {
	*x = PublishSnapshotResponse{}
	mi := &file_orange_config_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSnapshotResponse) ProtoMessage() {}

func (x *PublishSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSnapshotResponse.ProtoReflect.Descriptor instead.
func (*PublishSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_orange_config_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

var File_orange_config_admin_v1_admin_proto protoreflect.FileDescriptor

const file_orange_config_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\"orange/config/admin/v1/admin.proto\x12\x16orange.config.admin.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!orange/auth/v1/auth_options.proto\"\x18\n" +
	"\x16PublishSnapshotRequest\"\x19\n" +
	"\x17PublishSnapshotResponse2\x99\x01\n" +
	"\x12ConfigAdminService\x12\x82\x01\n" +
	"\x0fPublishSnapshot\x12..orange.config.admin.v1.PublishSnapshotRequest\x1a/.orange.config.admin.v1.PublishSnapshotResponse\"\x0e\xc2\xf3\x18\n" +
	"\n" +
	"\x01\x01\x12\x05adminB\xdd\x01\n" +
	"\x1acom.orange.config.admin.v1B\n" +
	"AdminProtoP\x01Z8github.com/dio/orange/api/orange/config/admin/v1;adminv1\xa2\x02\x03OCA\xaa\x02\x16Orange.Config.Admin.V1\xca\x02\x16Orange\\Config\\Admin\\V1\xe2\x02\"Orange\\Config\\Admin\\V1\\GPBMetadata\xea\x02\x19Orange::Config::Admin::V1b\x06proto3"

var (
	file_orange_config_admin_v1_admin_proto_rawDescOnce sync.Once
	file_orange_config_admin_v1_admin_proto_rawDescData []byte
)

func file_orange_config_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_orange_config_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_orange_config_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orange_config_admin_v1_admin_proto_rawDesc), len(file_orange_config_admin_v1_admin_proto_rawDesc)))
	})
	return file_orange_config_admin_v1_admin_proto_rawDescData
}

var file_orange_config_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orange_config_admin_v1_admin_proto_goTypes = []any{
	(*PublishSnapshotRequest)(nil),  // 0: orange.config.admin.v1.PublishSnapshotRequest
	(*PublishSnapshotResponse)(nil), // 1: orange.config.admin.v1.PublishSnapshotResponse
}
var file_orange_config_admin_v1_admin_proto_depIdxs = []int32{
	0, // 0: orange.config.admin.v1.ConfigAdminService.PublishSnapshot:input_type -> orange.config.admin.v1.PublishSnapshotRequest
	1, // 1: orange.config.admin.v1.ConfigAdminService.PublishSnapshot:output_type -> orange.config.admin.v1.PublishSnapshotResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orange_config_admin_v1_admin_proto_init() }
func file_orange_config_admin_v1_admin_proto_init() {
	if File_orange_config_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orange_config_admin_v1_admin_proto_rawDesc), len(file_orange_config_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orange_config_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_orange_config_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_orange_config_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_orange_config_admin_v1_admin_proto = out.File
	file_orange_config_admin_v1_admin_proto_goTypes = nil
	file_orange_config_admin_v1_admin_proto_depIdxs = nil
}
