// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: orange/inspect/v1/inspection.proto

package inspectv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dio/orange/api/orange/inspect/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InspectionServiceName is the fully-qualified name of the InspectionService service.
	InspectionServiceName = "orange.inspect.v1.InspectionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InspectionServiceStatusProcedure is the fully-qualified name of the InspectionService's Status
	// RPC.
	InspectionServiceStatusProcedure = "/orange.inspect.v1.InspectionService/Status"
	// InspectionServiceGenerationProcedure is the fully-qualified name of the InspectionService's
	// Generation RPC.
	InspectionServiceGenerationProcedure = "/orange.inspect.v1.InspectionService/Generation"
	// InspectionServiceScopesProcedure is the fully-qualified name of the InspectionService's Scopes
	// RPC.
	InspectionServiceScopesProcedure = "/orange.inspect.v1.InspectionService/Scopes"
	// InspectionServiceProvidersProcedure is the fully-qualified name of the InspectionService's
	// Providers RPC.
	InspectionServiceProvidersProcedure = "/orange.inspect.v1.InspectionService/Providers"
	// InspectionServiceModelsProcedure is the fully-qualified name of the InspectionService's Models
	// RPC.
	InspectionServiceModelsProcedure = "/orange.inspect.v1.InspectionService/Models"
	// InspectionServiceResolveLLMProcedure is the fully-qualified name of the InspectionService's
	// ResolveLLM RPC.
	InspectionServiceResolveLLMProcedure = "/orange.inspect.v1.InspectionService/ResolveLLM"
	// InspectionServiceResolveMCPProcedure is the fully-qualified name of the InspectionService's
	// ResolveMCP RPC.
	InspectionServiceResolveMCPProcedure = "/orange.inspect.v1.InspectionService/ResolveMCP"
	// InspectionServiceMatchViewProcedure is the fully-qualified name of the InspectionService's
	// MatchView RPC.
	InspectionServiceMatchViewProcedure = "/orange.inspect.v1.InspectionService/MatchView"
	// InspectionServicePickViewProcedure is the fully-qualified name of the InspectionService's
	// PickView RPC.
	InspectionServicePickViewProcedure = "/orange.inspect.v1.InspectionService/PickView"
	// InspectionServiceAdaptViewProcedure is the fully-qualified name of the InspectionService's
	// AdaptView RPC.
	InspectionServiceAdaptViewProcedure = "/orange.inspect.v1.InspectionService/AdaptView"
)

// InspectionServiceClient is a client for the orange.inspect.v1.InspectionService service.
type InspectionServiceClient interface {
	// Status returns protocol compatibility and current generation summary.
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	// Generation returns the active configuration generation metadata.
	Generation(context.Context, *connect.Request[v1.GenerationRequest]) (*connect.Response[v1.GenerationResponse], error)
	// Scopes lists scopes available in the active configuration.
	Scopes(context.Context, *connect.Request[v1.ScopesRequest]) (*connect.Response[v1.ScopesResponse], error)
	// Providers lists LLM providers in the active configuration.
	Providers(context.Context, *connect.Request[v1.ProvidersRequest]) (*connect.Response[v1.ProvidersResponse], error)
	// Models lists client-facing LLM models in the active configuration.
	Models(context.Context, *connect.Request[v1.ModelsRequest]) (*connect.Response[v1.ModelsResponse], error)
	// ResolveLLM resolves a principal and requested model against the active view.
	ResolveLLM(context.Context, *connect.Request[v1.ResolveLLMRequest]) (*connect.Response[v1.ResolveLLMResponse], error)
	// ResolveMCP resolves an MCP path/profile query against the active view.
	ResolveMCP(context.Context, *connect.Request[v1.ResolveMCPRequest]) (*connect.Response[v1.ResolveMCPResponse], error)
	// MatchView returns the runtime match diagnostic view.
	MatchView(context.Context, *connect.Request[v1.MatchViewRequest]) (*connect.Response[v1.MatchViewResponse], error)
	// PickView returns the runtime upstream-pick diagnostic view.
	PickView(context.Context, *connect.Request[v1.PickViewRequest]) (*connect.Response[v1.PickViewResponse], error)
	// AdaptView returns the runtime provider-adaptation diagnostic view.
	AdaptView(context.Context, *connect.Request[v1.AdaptViewRequest]) (*connect.Response[v1.AdaptViewResponse], error)
}

// NewInspectionServiceClient constructs a client for the orange.inspect.v1.InspectionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInspectionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InspectionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	inspectionServiceMethods := v1.File_orange_inspect_v1_inspection_proto.Services().ByName("InspectionService").Methods()
	return &inspectionServiceClient{
		status: connect.NewClient[v1.StatusRequest, v1.StatusResponse](
			httpClient,
			baseURL+InspectionServiceStatusProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		generation: connect.NewClient[v1.GenerationRequest, v1.GenerationResponse](
			httpClient,
			baseURL+InspectionServiceGenerationProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("Generation")),
			connect.WithClientOptions(opts...),
		),
		scopes: connect.NewClient[v1.ScopesRequest, v1.ScopesResponse](
			httpClient,
			baseURL+InspectionServiceScopesProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("Scopes")),
			connect.WithClientOptions(opts...),
		),
		providers: connect.NewClient[v1.ProvidersRequest, v1.ProvidersResponse](
			httpClient,
			baseURL+InspectionServiceProvidersProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("Providers")),
			connect.WithClientOptions(opts...),
		),
		models: connect.NewClient[v1.ModelsRequest, v1.ModelsResponse](
			httpClient,
			baseURL+InspectionServiceModelsProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("Models")),
			connect.WithClientOptions(opts...),
		),
		resolveLLM: connect.NewClient[v1.ResolveLLMRequest, v1.ResolveLLMResponse](
			httpClient,
			baseURL+InspectionServiceResolveLLMProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("ResolveLLM")),
			connect.WithClientOptions(opts...),
		),
		resolveMCP: connect.NewClient[v1.ResolveMCPRequest, v1.ResolveMCPResponse](
			httpClient,
			baseURL+InspectionServiceResolveMCPProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("ResolveMCP")),
			connect.WithClientOptions(opts...),
		),
		matchView: connect.NewClient[v1.MatchViewRequest, v1.MatchViewResponse](
			httpClient,
			baseURL+InspectionServiceMatchViewProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("MatchView")),
			connect.WithClientOptions(opts...),
		),
		pickView: connect.NewClient[v1.PickViewRequest, v1.PickViewResponse](
			httpClient,
			baseURL+InspectionServicePickViewProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("PickView")),
			connect.WithClientOptions(opts...),
		),
		adaptView: connect.NewClient[v1.AdaptViewRequest, v1.AdaptViewResponse](
			httpClient,
			baseURL+InspectionServiceAdaptViewProcedure,
			connect.WithSchema(inspectionServiceMethods.ByName("AdaptView")),
			connect.WithClientOptions(opts...),
		),
	}
}

// inspectionServiceClient implements InspectionServiceClient.
type inspectionServiceClient struct {
	status     *connect.Client[v1.StatusRequest, v1.StatusResponse]
	generation *connect.Client[v1.GenerationRequest, v1.GenerationResponse]
	scopes     *connect.Client[v1.ScopesRequest, v1.ScopesResponse]
	providers  *connect.Client[v1.ProvidersRequest, v1.ProvidersResponse]
	models     *connect.Client[v1.ModelsRequest, v1.ModelsResponse]
	resolveLLM *connect.Client[v1.ResolveLLMRequest, v1.ResolveLLMResponse]
	resolveMCP *connect.Client[v1.ResolveMCPRequest, v1.ResolveMCPResponse]
	matchView  *connect.Client[v1.MatchViewRequest, v1.MatchViewResponse]
	pickView   *connect.Client[v1.PickViewRequest, v1.PickViewResponse]
	adaptView  *connect.Client[v1.AdaptViewRequest, v1.AdaptViewResponse]
}

// Status calls orange.inspect.v1.InspectionService.Status.
func (c *inspectionServiceClient) Status(ctx context.Context, req *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// Generation calls orange.inspect.v1.InspectionService.Generation.
func (c *inspectionServiceClient) Generation(ctx context.Context, req *connect.Request[v1.GenerationRequest]) (*connect.Response[v1.GenerationResponse], error) {
	return c.generation.CallUnary(ctx, req)
}

// Scopes calls orange.inspect.v1.InspectionService.Scopes.
func (c *inspectionServiceClient) Scopes(ctx context.Context, req *connect.Request[v1.ScopesRequest]) (*connect.Response[v1.ScopesResponse], error) {
	return c.scopes.CallUnary(ctx, req)
}

// Providers calls orange.inspect.v1.InspectionService.Providers.
func (c *inspectionServiceClient) Providers(ctx context.Context, req *connect.Request[v1.ProvidersRequest]) (*connect.Response[v1.ProvidersResponse], error) {
	return c.providers.CallUnary(ctx, req)
}

// Models calls orange.inspect.v1.InspectionService.Models.
func (c *inspectionServiceClient) Models(ctx context.Context, req *connect.Request[v1.ModelsRequest]) (*connect.Response[v1.ModelsResponse], error) {
	return c.models.CallUnary(ctx, req)
}

// ResolveLLM calls orange.inspect.v1.InspectionService.ResolveLLM.
func (c *inspectionServiceClient) ResolveLLM(ctx context.Context, req *connect.Request[v1.ResolveLLMRequest]) (*connect.Response[v1.ResolveLLMResponse], error) {
	return c.resolveLLM.CallUnary(ctx, req)
}

// ResolveMCP calls orange.inspect.v1.InspectionService.ResolveMCP.
func (c *inspectionServiceClient) ResolveMCP(ctx context.Context, req *connect.Request[v1.ResolveMCPRequest]) (*connect.Response[v1.ResolveMCPResponse], error) {
	return c.resolveMCP.CallUnary(ctx, req)
}

// MatchView calls orange.inspect.v1.InspectionService.MatchView.
func (c *inspectionServiceClient) MatchView(ctx context.Context, req *connect.Request[v1.MatchViewRequest]) (*connect.Response[v1.MatchViewResponse], error) {
	return c.matchView.CallUnary(ctx, req)
}

// PickView calls orange.inspect.v1.InspectionService.PickView.
func (c *inspectionServiceClient) PickView(ctx context.Context, req *connect.Request[v1.PickViewRequest]) (*connect.Response[v1.PickViewResponse], error) {
	return c.pickView.CallUnary(ctx, req)
}

// AdaptView calls orange.inspect.v1.InspectionService.AdaptView.
func (c *inspectionServiceClient) AdaptView(ctx context.Context, req *connect.Request[v1.AdaptViewRequest]) (*connect.Response[v1.AdaptViewResponse], error) {
	return c.adaptView.CallUnary(ctx, req)
}

// InspectionServiceHandler is an implementation of the orange.inspect.v1.InspectionService service.
type InspectionServiceHandler interface {
	// Status returns protocol compatibility and current generation summary.
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	// Generation returns the active configuration generation metadata.
	Generation(context.Context, *connect.Request[v1.GenerationRequest]) (*connect.Response[v1.GenerationResponse], error)
	// Scopes lists scopes available in the active configuration.
	Scopes(context.Context, *connect.Request[v1.ScopesRequest]) (*connect.Response[v1.ScopesResponse], error)
	// Providers lists LLM providers in the active configuration.
	Providers(context.Context, *connect.Request[v1.ProvidersRequest]) (*connect.Response[v1.ProvidersResponse], error)
	// Models lists client-facing LLM models in the active configuration.
	Models(context.Context, *connect.Request[v1.ModelsRequest]) (*connect.Response[v1.ModelsResponse], error)
	// ResolveLLM resolves a principal and requested model against the active view.
	ResolveLLM(context.Context, *connect.Request[v1.ResolveLLMRequest]) (*connect.Response[v1.ResolveLLMResponse], error)
	// ResolveMCP resolves an MCP path/profile query against the active view.
	ResolveMCP(context.Context, *connect.Request[v1.ResolveMCPRequest]) (*connect.Response[v1.ResolveMCPResponse], error)
	// MatchView returns the runtime match diagnostic view.
	MatchView(context.Context, *connect.Request[v1.MatchViewRequest]) (*connect.Response[v1.MatchViewResponse], error)
	// PickView returns the runtime upstream-pick diagnostic view.
	PickView(context.Context, *connect.Request[v1.PickViewRequest]) (*connect.Response[v1.PickViewResponse], error)
	// AdaptView returns the runtime provider-adaptation diagnostic view.
	AdaptView(context.Context, *connect.Request[v1.AdaptViewRequest]) (*connect.Response[v1.AdaptViewResponse], error)
}

// NewInspectionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInspectionServiceHandler(svc InspectionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	inspectionServiceMethods := v1.File_orange_inspect_v1_inspection_proto.Services().ByName("InspectionService").Methods()
	inspectionServiceStatusHandler := connect.NewUnaryHandler(
		InspectionServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(inspectionServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	inspectionServiceGenerationHandler := connect.NewUnaryHandler(
		InspectionServiceGenerationProcedure,
		svc.Generation,
		connect.WithSchema(inspectionServiceMethods.ByName("Generation")),
		connect.WithHandlerOptions(opts...),
	)
	inspectionServiceScopesHandler := connect.NewUnaryHandler(
		InspectionServiceScopesProcedure,
		svc.Scopes,
		connect.WithSchema(inspectionServiceMethods.ByName("Scopes")),
		connect.WithHandlerOptions(opts...),
	)
	inspectionServiceProvidersHandler := connect.NewUnaryHandler(
		InspectionServiceProvidersProcedure,
		svc.Providers,
		connect.WithSchema(inspectionServiceMethods.ByName("Providers")),
		connect.WithHandlerOptions(opts...),
	)
	inspectionServiceModelsHandler := connect.NewUnaryHandler(
		InspectionServiceModelsProcedure,
		svc.Models,
		connect.WithSchema(inspectionServiceMethods.ByName("Models")),
		connect.WithHandlerOptions(opts...),
	)
	inspectionServiceResolveLLMHandler := connect.NewUnaryHandler(
		InspectionServiceResolveLLMProcedure,
		svc.ResolveLLM,
		connect.WithSchema(inspectionServiceMethods.ByName("ResolveLLM")),
		connect.WithHandlerOptions(opts...),
	)
	inspectionServiceResolveMCPHandler := connect.NewUnaryHandler(
		InspectionServiceResolveMCPProcedure,
		svc.ResolveMCP,
		connect.WithSchema(inspectionServiceMethods.ByName("ResolveMCP")),
		connect.WithHandlerOptions(opts...),
	)
	inspectionServiceMatchViewHandler := connect.NewUnaryHandler(
		InspectionServiceMatchViewProcedure,
		svc.MatchView,
		connect.WithSchema(inspectionServiceMethods.ByName("MatchView")),
		connect.WithHandlerOptions(opts...),
	)
	inspectionServicePickViewHandler := connect.NewUnaryHandler(
		InspectionServicePickViewProcedure,
		svc.PickView,
		connect.WithSchema(inspectionServiceMethods.ByName("PickView")),
		connect.WithHandlerOptions(opts...),
	)
	inspectionServiceAdaptViewHandler := connect.NewUnaryHandler(
		InspectionServiceAdaptViewProcedure,
		svc.AdaptView,
		connect.WithSchema(inspectionServiceMethods.ByName("AdaptView")),
		connect.WithHandlerOptions(opts...),
	)
	return "/orange.inspect.v1.InspectionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InspectionServiceStatusProcedure:
			inspectionServiceStatusHandler.ServeHTTP(w, r)
		case InspectionServiceGenerationProcedure:
			inspectionServiceGenerationHandler.ServeHTTP(w, r)
		case InspectionServiceScopesProcedure:
			inspectionServiceScopesHandler.ServeHTTP(w, r)
		case InspectionServiceProvidersProcedure:
			inspectionServiceProvidersHandler.ServeHTTP(w, r)
		case InspectionServiceModelsProcedure:
			inspectionServiceModelsHandler.ServeHTTP(w, r)
		case InspectionServiceResolveLLMProcedure:
			inspectionServiceResolveLLMHandler.ServeHTTP(w, r)
		case InspectionServiceResolveMCPProcedure:
			inspectionServiceResolveMCPHandler.ServeHTTP(w, r)
		case InspectionServiceMatchViewProcedure:
			inspectionServiceMatchViewHandler.ServeHTTP(w, r)
		case InspectionServicePickViewProcedure:
			inspectionServicePickViewHandler.ServeHTTP(w, r)
		case InspectionServiceAdaptViewProcedure:
			inspectionServiceAdaptViewHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInspectionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInspectionServiceHandler struct{}

func (UnimplementedInspectionServiceHandler) Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.inspect.v1.InspectionService.Status is not implemented"))
}

func (UnimplementedInspectionServiceHandler) Generation(context.Context, *connect.Request[v1.GenerationRequest]) (*connect.Response[v1.GenerationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.inspect.v1.InspectionService.Generation is not implemented"))
}

func (UnimplementedInspectionServiceHandler) Scopes(context.Context, *connect.Request[v1.ScopesRequest]) (*connect.Response[v1.ScopesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.inspect.v1.InspectionService.Scopes is not implemented"))
}

func (UnimplementedInspectionServiceHandler) Providers(context.Context, *connect.Request[v1.ProvidersRequest]) (*connect.Response[v1.ProvidersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.inspect.v1.InspectionService.Providers is not implemented"))
}

func (UnimplementedInspectionServiceHandler) Models(context.Context, *connect.Request[v1.ModelsRequest]) (*connect.Response[v1.ModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.inspect.v1.InspectionService.Models is not implemented"))
}

func (UnimplementedInspectionServiceHandler) ResolveLLM(context.Context, *connect.Request[v1.ResolveLLMRequest]) (*connect.Response[v1.ResolveLLMResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.inspect.v1.InspectionService.ResolveLLM is not implemented"))
}

func (UnimplementedInspectionServiceHandler) ResolveMCP(context.Context, *connect.Request[v1.ResolveMCPRequest]) (*connect.Response[v1.ResolveMCPResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.inspect.v1.InspectionService.ResolveMCP is not implemented"))
}

func (UnimplementedInspectionServiceHandler) MatchView(context.Context, *connect.Request[v1.MatchViewRequest]) (*connect.Response[v1.MatchViewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.inspect.v1.InspectionService.MatchView is not implemented"))
}

func (UnimplementedInspectionServiceHandler) PickView(context.Context, *connect.Request[v1.PickViewRequest]) (*connect.Response[v1.PickViewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.inspect.v1.InspectionService.PickView is not implemented"))
}

func (UnimplementedInspectionServiceHandler) AdaptView(context.Context, *connect.Request[v1.AdaptViewRequest]) (*connect.Response[v1.AdaptViewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orange.inspect.v1.InspectionService.AdaptView is not implemented"))
}
