// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orange/inspect/v1/inspection.proto

package inspectv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/dio/orange/api/orange/auth/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatusRequest requests inspection API status.
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_protocol_version is the highest inspection protocol version the
	// caller understands. Zero means unknown.
	ClientProtocolVersion uint32 `protobuf:"varint,1,opt,name=client_protocol_version,json=clientProtocolVersion,proto3" json:"client_protocol_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetClientProtocolVersion() uint32 {
	if x != nil {
		return x.ClientProtocolVersion
	}
	return 0
}

// StatusResponse describes inspection protocol compatibility and availability.
type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	HasGeneration   bool                   `protobuf:"varint,3,opt,name=has_generation,json=hasGeneration,proto3" json:"has_generation,omitempty"`
	Generation      *GenerationInfo        `protobuf:"bytes,4,opt,name=generation,proto3" json:"generation,omitempty"`
	ObservedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *StatusResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *StatusResponse) GetHasGeneration() bool {
	if x != nil {
		return x.HasGeneration
	}
	return false
}

func (x *StatusResponse) GetGeneration() *GenerationInfo {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *StatusResponse) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

// GenerationRequest requests active generation metadata.
type GenerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationRequest) Reset() {
	*x = GenerationRequest{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationRequest) ProtoMessage() {}

func (x *GenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationRequest.ProtoReflect.Descriptor instead.
func (*GenerationRequest) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{2}
}

// GenerationResponse returns active generation metadata.
type GenerationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Generation      *GenerationInfo        `protobuf:"bytes,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerationResponse) Reset() {
	*x = GenerationResponse{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationResponse) ProtoMessage() {}

func (x *GenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationResponse.ProtoReflect.Descriptor instead.
func (*GenerationResponse) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{3}
}

func (x *GenerationResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *GenerationResponse) GetGeneration() *GenerationInfo {
	if x != nil {
		return x.Generation
	}
	return nil
}

// ScopesRequest requests active scopes.
type ScopesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopesRequest) Reset() {
	*x = ScopesRequest{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopesRequest) ProtoMessage() {}

func (x *ScopesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopesRequest.ProtoReflect.Descriptor instead.
func (*ScopesRequest) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{4}
}

// ScopesResponse returns active scopes.
type ScopesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *GenerationInfo        `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Scopes        []*ScopeInfo           `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopesResponse) Reset() {
	*x = ScopesResponse{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopesResponse) ProtoMessage() {}

func (x *ScopesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopesResponse.ProtoReflect.Descriptor instead.
func (*ScopesResponse) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{5}
}

func (x *ScopesResponse) GetGeneration() *GenerationInfo {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *ScopesResponse) GetScopes() []*ScopeInfo {
	if x != nil {
		return x.Scopes
	}
	return nil
}

// ProvidersRequest requests active providers.
type ProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvidersRequest) Reset() {
	*x = ProvidersRequest{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvidersRequest) ProtoMessage() {}

func (x *ProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvidersRequest.ProtoReflect.Descriptor instead.
func (*ProvidersRequest) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{6}
}

// ProvidersResponse returns active providers.
type ProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *GenerationInfo        `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Providers     []*ProviderInfo        `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvidersResponse) Reset() {
	*x = ProvidersResponse{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvidersResponse) ProtoMessage() {}

func (x *ProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvidersResponse.ProtoReflect.Descriptor instead.
func (*ProvidersResponse) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{7}
}

func (x *ProvidersResponse) GetGeneration() *GenerationInfo {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *ProvidersResponse) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

// ModelsRequest requests active models.
type ModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsRequest) Reset() {
	*x = ModelsRequest{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsRequest) ProtoMessage() {}

func (x *ModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsRequest.ProtoReflect.Descriptor instead.
func (*ModelsRequest) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{8}
}

// ModelsResponse returns active models.
type ModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *GenerationInfo        `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Models        []*ModelInfo           `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsResponse) Reset() {
	*x = ModelsResponse{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsResponse) ProtoMessage() {}

func (x *ModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsResponse.ProtoReflect.Descriptor instead.
func (*ModelsResponse) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{9}
}

func (x *ModelsResponse) GetGeneration() *GenerationInfo {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *ModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

// ResolveLLMRequest asks the server to resolve an LLM route without executing a
// request or resolving provider secrets.
type ResolveLLMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	PrincipalSlug string                 `protobuf:"bytes,2,opt,name=principal_slug,json=principalSlug,proto3" json:"principal_slug,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveLLMRequest) Reset() {
	*x = ResolveLLMRequest{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveLLMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveLLMRequest) ProtoMessage() {}

func (x *ResolveLLMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveLLMRequest.ProtoReflect.Descriptor instead.
func (*ResolveLLMRequest) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{10}
}

func (x *ResolveLLMRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ResolveLLMRequest) GetPrincipalSlug() string {
	if x != nil {
		return x.PrincipalSlug
	}
	return ""
}

func (x *ResolveLLMRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// ResolveLLMResponse returns a sanitized LLM resolution result.
type ResolveLLMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *GenerationInfo        `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Matched       bool                   `protobuf:"varint,2,opt,name=matched,proto3" json:"matched,omitempty"`
	Route         *LLMRoute              `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	Diagnostics   []string               `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveLLMResponse) Reset() {
	*x = ResolveLLMResponse{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveLLMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveLLMResponse) ProtoMessage() {}

func (x *ResolveLLMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveLLMResponse.ProtoReflect.Descriptor instead.
func (*ResolveLLMResponse) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveLLMResponse) GetGeneration() *GenerationInfo {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *ResolveLLMResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *ResolveLLMResponse) GetRoute() *LLMRoute {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *ResolveLLMResponse) GetDiagnostics() []string {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

// ResolveMCPRequest asks the server to resolve an MCP path/profile query.
type ResolveMCPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	PrincipalSlug string                 `protobuf:"bytes,2,opt,name=principal_slug,json=principalSlug,proto3" json:"principal_slug,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMCPRequest) Reset() {
	*x = ResolveMCPRequest{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMCPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMCPRequest) ProtoMessage() {}

func (x *ResolveMCPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMCPRequest.ProtoReflect.Descriptor instead.
func (*ResolveMCPRequest) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveMCPRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ResolveMCPRequest) GetPrincipalSlug() string {
	if x != nil {
		return x.PrincipalSlug
	}
	return ""
}

func (x *ResolveMCPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ResolveMCPResponse returns a sanitized MCP resolution result.
type ResolveMCPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *GenerationInfo        `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Matched       bool                   `protobuf:"varint,2,opt,name=matched,proto3" json:"matched,omitempty"`
	Route         *MCPRoute              `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	Diagnostics   []string               `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMCPResponse) Reset() {
	*x = ResolveMCPResponse{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMCPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMCPResponse) ProtoMessage() {}

func (x *ResolveMCPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMCPResponse.ProtoReflect.Descriptor instead.
func (*ResolveMCPResponse) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{13}
}

func (x *ResolveMCPResponse) GetGeneration() *GenerationInfo {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *ResolveMCPResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *ResolveMCPResponse) GetRoute() *MCPRoute {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *ResolveMCPResponse) GetDiagnostics() []string {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

// MatchViewRequest requests the match diagnostic view.
type MatchViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchViewRequest) Reset() {
	*x = MatchViewRequest{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchViewRequest) ProtoMessage() {}

func (x *MatchViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchViewRequest.ProtoReflect.Descriptor instead.
func (*MatchViewRequest) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{14}
}

func (x *MatchViewRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// PickViewRequest requests the upstream-pick diagnostic view.
type PickViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickViewRequest) Reset() {
	*x = PickViewRequest{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickViewRequest) ProtoMessage() {}

func (x *PickViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickViewRequest.ProtoReflect.Descriptor instead.
func (*PickViewRequest) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{15}
}

func (x *PickViewRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// AdaptViewRequest requests the provider-adaptation diagnostic view.
type AdaptViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptViewRequest) Reset() {
	*x = AdaptViewRequest{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptViewRequest) ProtoMessage() {}

func (x *AdaptViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptViewRequest.ProtoReflect.Descriptor instead.
func (*AdaptViewRequest) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{16}
}

func (x *AdaptViewRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// MatchViewResponse returns the match diagnostic view as a typed protobuf
// Struct suitable for JSON output.
type MatchViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *GenerationInfo        `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	View          *structpb.Struct       `protobuf:"bytes,2,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchViewResponse) Reset() {
	*x = MatchViewResponse{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchViewResponse) ProtoMessage() {}

func (x *MatchViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchViewResponse.ProtoReflect.Descriptor instead.
func (*MatchViewResponse) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{17}
}

func (x *MatchViewResponse) GetGeneration() *GenerationInfo {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *MatchViewResponse) GetView() *structpb.Struct {
	if x != nil {
		return x.View
	}
	return nil
}

// PickViewResponse returns the upstream-pick diagnostic view as a typed
// protobuf Struct suitable for JSON output.
type PickViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *GenerationInfo        `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	View          *structpb.Struct       `protobuf:"bytes,2,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickViewResponse) Reset() {
	*x = PickViewResponse{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickViewResponse) ProtoMessage() {}

func (x *PickViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickViewResponse.ProtoReflect.Descriptor instead.
func (*PickViewResponse) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{18}
}

func (x *PickViewResponse) GetGeneration() *GenerationInfo {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *PickViewResponse) GetView() *structpb.Struct {
	if x != nil {
		return x.View
	}
	return nil
}

// AdaptViewResponse returns the provider-adaptation diagnostic view as a typed
// protobuf Struct suitable for JSON output.
type AdaptViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *GenerationInfo        `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	View          *structpb.Struct       `protobuf:"bytes,2,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptViewResponse) Reset() {
	*x = AdaptViewResponse{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptViewResponse) ProtoMessage() {}

func (x *AdaptViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptViewResponse.ProtoReflect.Descriptor instead.
func (*AdaptViewResponse) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{19}
}

func (x *AdaptViewResponse) GetGeneration() *GenerationInfo {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *AdaptViewResponse) GetView() *structpb.Struct {
	if x != nil {
		return x.View
	}
	return nil
}

// GenerationInfo describes one immutable opened configuration snapshot.
type GenerationInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GenerationId   string                 `protobuf:"bytes,1,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	Revision       string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	SourceRevision string                 `protobuf:"bytes,3,opt,name=source_revision,json=sourceRevision,proto3" json:"source_revision,omitempty"`
	ScopeKind      string                 `protobuf:"bytes,4,opt,name=scope_kind,json=scopeKind,proto3" json:"scope_kind,omitempty"`
	ScopeId        string                 `protobuf:"bytes,5,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	Scopes         []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	MapVersion     uint64                 `protobuf:"varint,7,opt,name=map_version,json=mapVersion,proto3" json:"map_version,omitempty"`
	MapRevision    uint64                 `protobuf:"varint,8,opt,name=map_revision,json=mapRevision,proto3" json:"map_revision,omitempty"`
	Components     []*ComponentInfo       `protobuf:"bytes,9,rep,name=components,proto3" json:"components,omitempty"`
	ObservedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerationInfo) Reset() {
	*x = GenerationInfo{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationInfo) ProtoMessage() {}

func (x *GenerationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationInfo.ProtoReflect.Descriptor instead.
func (*GenerationInfo) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{20}
}

func (x *GenerationInfo) GetGenerationId() string {
	if x != nil {
		return x.GenerationId
	}
	return ""
}

func (x *GenerationInfo) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *GenerationInfo) GetSourceRevision() string {
	if x != nil {
		return x.SourceRevision
	}
	return ""
}

func (x *GenerationInfo) GetScopeKind() string {
	if x != nil {
		return x.ScopeKind
	}
	return ""
}

func (x *GenerationInfo) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *GenerationInfo) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *GenerationInfo) GetMapVersion() uint64 {
	if x != nil {
		return x.MapVersion
	}
	return 0
}

func (x *GenerationInfo) GetMapRevision() uint64 {
	if x != nil {
		return x.MapRevision
	}
	return 0
}

func (x *GenerationInfo) GetComponents() []*ComponentInfo {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *GenerationInfo) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

// ComponentInfo summarizes one opened component bundle.
type ComponentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Resource       string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Component      string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Version        uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Checksum       uint64                 `protobuf:"varint,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size           uint64                 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	SourceRevision string                 `protobuf:"bytes,7,opt,name=source_revision,json=sourceRevision,proto3" json:"source_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComponentInfo) Reset() {
	*x = ComponentInfo{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentInfo) ProtoMessage() {}

func (x *ComponentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentInfo.ProtoReflect.Descriptor instead.
func (*ComponentInfo) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{21}
}

func (x *ComponentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComponentInfo) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ComponentInfo) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ComponentInfo) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ComponentInfo) GetChecksum() uint64 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *ComponentInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ComponentInfo) GetSourceRevision() string {
	if x != nil {
		return x.SourceRevision
	}
	return ""
}

// ScopeInfo describes one configured scope.
type ScopeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeInfo) Reset() {
	*x = ScopeInfo{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeInfo) ProtoMessage() {}

func (x *ScopeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeInfo.ProtoReflect.Descriptor instead.
func (*ScopeInfo) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{22}
}

func (x *ScopeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScopeInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ScopeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ProviderInfo describes one LLM provider without exposing secret bytes.
type ProviderInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind              string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Endpoint          string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	RedactedSecretRef string                 `protobuf:"bytes,4,opt,name=redacted_secret_ref,json=redactedSecretRef,proto3" json:"redacted_secret_ref,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{23}
}

func (x *ProviderInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ProviderInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ProviderInfo) GetRedactedSecretRef() string {
	if x != nil {
		return x.RedactedSecretRef
	}
	return ""
}

func (x *ProviderInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ModelInfo describes one client-facing model.
type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{24}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ModelInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// LLMRoute describes a resolved LLM request path.
type LLMRoute struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Provider          string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderKind      string                 `protobuf:"bytes,3,opt,name=provider_kind,json=providerKind,proto3" json:"provider_kind,omitempty"`
	BackendModel      string                 `protobuf:"bytes,4,opt,name=backend_model,json=backendModel,proto3" json:"backend_model,omitempty"`
	Partition         string                 `protobuf:"bytes,5,opt,name=partition,proto3" json:"partition,omitempty"`
	RedactedSecretRef string                 `protobuf:"bytes,6,opt,name=redacted_secret_ref,json=redactedSecretRef,proto3" json:"redacted_secret_ref,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LLMRoute) Reset() {
	*x = LLMRoute{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRoute) ProtoMessage() {}

func (x *LLMRoute) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRoute.ProtoReflect.Descriptor instead.
func (*LLMRoute) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{25}
}

func (x *LLMRoute) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMRoute) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMRoute) GetProviderKind() string {
	if x != nil {
		return x.ProviderKind
	}
	return ""
}

func (x *LLMRoute) GetBackendModel() string {
	if x != nil {
		return x.BackendModel
	}
	return ""
}

func (x *LLMRoute) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *LLMRoute) GetRedactedSecretRef() string {
	if x != nil {
		return x.RedactedSecretRef
	}
	return ""
}

// MCPRoute describes a resolved MCP request path.
type MCPRoute struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Server          string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Path            string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Endpoint        string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	RedactedAuthRef string                 `protobuf:"bytes,4,opt,name=redacted_auth_ref,json=redactedAuthRef,proto3" json:"redacted_auth_ref,omitempty"`
	Tools           []*MCPTool             `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MCPRoute) Reset() {
	*x = MCPRoute{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPRoute) ProtoMessage() {}

func (x *MCPRoute) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPRoute.ProtoReflect.Descriptor instead.
func (*MCPRoute) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{26}
}

func (x *MCPRoute) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *MCPRoute) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MCPRoute) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *MCPRoute) GetRedactedAuthRef() string {
	if x != nil {
		return x.RedactedAuthRef
	}
	return ""
}

func (x *MCPRoute) GetTools() []*MCPTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

// MCPTool describes one MCP tool binding.
type MCPTool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPTool) Reset() {
	*x = MCPTool{}
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPTool) ProtoMessage() {}

func (x *MCPTool) ProtoReflect() protoreflect.Message {
	mi := &file_orange_inspect_v1_inspection_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPTool.ProtoReflect.Descriptor instead.
func (*MCPTool) Descriptor() ([]byte, []int) {
	return file_orange_inspect_v1_inspection_proto_rawDescGZIP(), []int{27}
}

func (x *MCPTool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPTool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_orange_inspect_v1_inspection_proto protoreflect.FileDescriptor

const file_orange_inspect_v1_inspection_proto_rawDesc = "" +
	"\n" +
	"\"orange/inspect/v1/inspection.proto\x12\x11orange.inspect.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!orange/auth/v1/auth_options.proto\"G\n" +
	"\rStatusRequest\x126\n" +
	"\x17client_protocol_version\x18\x01 \x01(\rR\x15clientProtocolVersion\"\x86\x02\n" +
	"\x0eStatusResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12%\n" +
	"\x0ehas_generation\x18\x03 \x01(\bR\rhasGeneration\x12A\n" +
	"\n" +
	"generation\x18\x04 \x01(\v2!.orange.inspect.v1.GenerationInfoR\n" +
	"generation\x12;\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"\x13\n" +
	"\x11GenerationRequest\"\x82\x01\n" +
	"\x12GenerationResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12A\n" +
	"\n" +
	"generation\x18\x02 \x01(\v2!.orange.inspect.v1.GenerationInfoR\n" +
	"generation\"\x0f\n" +
	"\rScopesRequest\"\x89\x01\n" +
	"\x0eScopesResponse\x12A\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2!.orange.inspect.v1.GenerationInfoR\n" +
	"generation\x124\n" +
	"\x06scopes\x18\x02 \x03(\v2\x1c.orange.inspect.v1.ScopeInfoR\x06scopes\"\x12\n" +
	"\x10ProvidersRequest\"\x95\x01\n" +
	"\x11ProvidersResponse\x12A\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2!.orange.inspect.v1.GenerationInfoR\n" +
	"generation\x12=\n" +
	"\tproviders\x18\x02 \x03(\v2\x1f.orange.inspect.v1.ProviderInfoR\tproviders\"\x0f\n" +
	"\rModelsRequest\"\x89\x01\n" +
	"\x0eModelsResponse\x12A\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2!.orange.inspect.v1.GenerationInfoR\n" +
	"generation\x124\n" +
	"\x06models\x18\x02 \x03(\v2\x1c.orange.inspect.v1.ModelInfoR\x06models\"x\n" +
	"\x11ResolveLLMRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12.\n" +
	"\x0eprincipal_slug\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\rprincipalSlug\x12\x1d\n" +
	"\x05model\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05model\"\xc6\x01\n" +
	"\x12ResolveLLMResponse\x12A\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2!.orange.inspect.v1.GenerationInfoR\n" +
	"generation\x12\x18\n" +
	"\amatched\x18\x02 \x01(\bR\amatched\x121\n" +
	"\x05route\x18\x03 \x01(\v2\x1b.orange.inspect.v1.LLMRouteR\x05route\x12 \n" +
	"\vdiagnostics\x18\x04 \x03(\tR\vdiagnostics\"m\n" +
	"\x11ResolveMCPRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12%\n" +
	"\x0eprincipal_slug\x18\x02 \x01(\tR\rprincipalSlug\x12\x1b\n" +
	"\x04path\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04path\"\xc6\x01\n" +
	"\x12ResolveMCPResponse\x12A\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2!.orange.inspect.v1.GenerationInfoR\n" +
	"generation\x12\x18\n" +
	"\amatched\x18\x02 \x01(\bR\amatched\x121\n" +
	"\x05route\x18\x03 \x01(\v2\x1b.orange.inspect.v1.MCPRouteR\x05route\x12 \n" +
	"\vdiagnostics\x18\x04 \x03(\tR\vdiagnostics\"(\n" +
	"\x10MatchViewRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"'\n" +
	"\x0fPickViewRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"(\n" +
	"\x10AdaptViewRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"\x83\x01\n" +
	"\x11MatchViewResponse\x12A\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2!.orange.inspect.v1.GenerationInfoR\n" +
	"generation\x12+\n" +
	"\x04view\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04view\"\x82\x01\n" +
	"\x10PickViewResponse\x12A\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2!.orange.inspect.v1.GenerationInfoR\n" +
	"generation\x12+\n" +
	"\x04view\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04view\"\x83\x01\n" +
	"\x11AdaptViewResponse\x12A\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2!.orange.inspect.v1.GenerationInfoR\n" +
	"generation\x12+\n" +
	"\x04view\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04view\"\x8f\x03\n" +
	"\x0eGenerationInfo\x12#\n" +
	"\rgeneration_id\x18\x01 \x01(\tR\fgenerationId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12'\n" +
	"\x0fsource_revision\x18\x03 \x01(\tR\x0esourceRevision\x12\x1d\n" +
	"\n" +
	"scope_kind\x18\x04 \x01(\tR\tscopeKind\x12\x19\n" +
	"\bscope_id\x18\x05 \x01(\tR\ascopeId\x12\x16\n" +
	"\x06scopes\x18\x06 \x03(\tR\x06scopes\x12\x1f\n" +
	"\vmap_version\x18\a \x01(\x04R\n" +
	"mapVersion\x12!\n" +
	"\fmap_revision\x18\b \x01(\x04R\vmapRevision\x12@\n" +
	"\n" +
	"components\x18\t \x03(\v2 .orange.inspect.v1.ComponentInfoR\n" +
	"components\x12;\n" +
	"\vobserved_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"\xcc\x01\n" +
	"\rComponentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\x04R\bchecksum\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x04R\x04size\x12'\n" +
	"\x0fsource_revision\x18\a \x01(\tR\x0esourceRevision\"C\n" +
	"\tScopeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x86\x02\n" +
	"\fProviderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12.\n" +
	"\x13redacted_secret_ref\x18\x04 \x01(\tR\x11redactedSecretRef\x12I\n" +
	"\bmetadata\x18\x05 \x03(\v2-.orange.inspect.v1.ProviderInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"\xd4\x01\n" +
	"\bLLMRoute\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12#\n" +
	"\rprovider_kind\x18\x03 \x01(\tR\fproviderKind\x12#\n" +
	"\rbackend_model\x18\x04 \x01(\tR\fbackendModel\x12\x1c\n" +
	"\tpartition\x18\x05 \x01(\tR\tpartition\x12.\n" +
	"\x13redacted_secret_ref\x18\x06 \x01(\tR\x11redactedSecretRef\"\xb0\x01\n" +
	"\bMCPRoute\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12*\n" +
	"\x11redacted_auth_ref\x18\x04 \x01(\tR\x0fredactedAuthRef\x120\n" +
	"\x05tools\x18\x05 \x03(\v2\x1a.orange.inspect.v1.MCPToolR\x05tools\"?\n" +
	"\aMCPTool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription2\xa2\b\n" +
	"\x11InspectionService\x12_\n" +
	"\x06Status\x12 .orange.inspect.v1.StatusRequest\x1a!.orange.inspect.v1.StatusResponse\"\x10\xea\xb5S\f\n" +
	"\x03\x01\x02\x03\x12\x05admin\x12k\n" +
	"\n" +
	"Generation\x12$.orange.inspect.v1.GenerationRequest\x1a%.orange.inspect.v1.GenerationResponse\"\x10\xea\xb5S\f\n" +
	"\x03\x01\x02\x03\x12\x05admin\x12_\n" +
	"\x06Scopes\x12 .orange.inspect.v1.ScopesRequest\x1a!.orange.inspect.v1.ScopesResponse\"\x10\xea\xb5S\f\n" +
	"\x03\x01\x02\x03\x12\x05admin\x12h\n" +
	"\tProviders\x12#.orange.inspect.v1.ProvidersRequest\x1a$.orange.inspect.v1.ProvidersResponse\"\x10\xea\xb5S\f\n" +
	"\x03\x01\x02\x03\x12\x05admin\x12_\n" +
	"\x06Models\x12 .orange.inspect.v1.ModelsRequest\x1a!.orange.inspect.v1.ModelsResponse\"\x10\xea\xb5S\f\n" +
	"\x03\x01\x02\x03\x12\x05admin\x12k\n" +
	"\n" +
	"ResolveLLM\x12$.orange.inspect.v1.ResolveLLMRequest\x1a%.orange.inspect.v1.ResolveLLMResponse\"\x10\xea\xb5S\f\n" +
	"\x03\x01\x02\x03\x12\x05admin\x12k\n" +
	"\n" +
	"ResolveMCP\x12$.orange.inspect.v1.ResolveMCPRequest\x1a%.orange.inspect.v1.ResolveMCPResponse\"\x10\xea\xb5S\f\n" +
	"\x03\x01\x02\x03\x12\x05admin\x12h\n" +
	"\tMatchView\x12#.orange.inspect.v1.MatchViewRequest\x1a$.orange.inspect.v1.MatchViewResponse\"\x10\xea\xb5S\f\n" +
	"\x03\x01\x02\x03\x12\x05admin\x12e\n" +
	"\bPickView\x12\".orange.inspect.v1.PickViewRequest\x1a#.orange.inspect.v1.PickViewResponse\"\x10\xea\xb5S\f\n" +
	"\x03\x01\x02\x03\x12\x05admin\x12h\n" +
	"\tAdaptView\x12#.orange.inspect.v1.AdaptViewRequest\x1a$.orange.inspect.v1.AdaptViewResponse\"\x10\xea\xb5S\f\n" +
	"\x03\x01\x02\x03\x12\x05adminB\xc5\x01\n" +
	"\x15com.orange.inspect.v1B\x0fInspectionProtoP\x01Z5github.com/dio/orange/api/orange/inspect/v1;inspectv1\xa2\x02\x03OIX\xaa\x02\x11Orange.Inspect.V1\xca\x02\x11Orange\\Inspect\\V1\xe2\x02\x1dOrange\\Inspect\\V1\\GPBMetadata\xea\x02\x13Orange::Inspect::V1b\x06proto3"

var (
	file_orange_inspect_v1_inspection_proto_rawDescOnce sync.Once
	file_orange_inspect_v1_inspection_proto_rawDescData []byte
)

func file_orange_inspect_v1_inspection_proto_rawDescGZIP() []byte {
	file_orange_inspect_v1_inspection_proto_rawDescOnce.Do(func() {
		file_orange_inspect_v1_inspection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orange_inspect_v1_inspection_proto_rawDesc), len(file_orange_inspect_v1_inspection_proto_rawDesc)))
	})
	return file_orange_inspect_v1_inspection_proto_rawDescData
}

var file_orange_inspect_v1_inspection_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_orange_inspect_v1_inspection_proto_goTypes = []any{
	(*StatusRequest)(nil),         // 0: orange.inspect.v1.StatusRequest
	(*StatusResponse)(nil),        // 1: orange.inspect.v1.StatusResponse
	(*GenerationRequest)(nil),     // 2: orange.inspect.v1.GenerationRequest
	(*GenerationResponse)(nil),    // 3: orange.inspect.v1.GenerationResponse
	(*ScopesRequest)(nil),         // 4: orange.inspect.v1.ScopesRequest
	(*ScopesResponse)(nil),        // 5: orange.inspect.v1.ScopesResponse
	(*ProvidersRequest)(nil),      // 6: orange.inspect.v1.ProvidersRequest
	(*ProvidersResponse)(nil),     // 7: orange.inspect.v1.ProvidersResponse
	(*ModelsRequest)(nil),         // 8: orange.inspect.v1.ModelsRequest
	(*ModelsResponse)(nil),        // 9: orange.inspect.v1.ModelsResponse
	(*ResolveLLMRequest)(nil),     // 10: orange.inspect.v1.ResolveLLMRequest
	(*ResolveLLMResponse)(nil),    // 11: orange.inspect.v1.ResolveLLMResponse
	(*ResolveMCPRequest)(nil),     // 12: orange.inspect.v1.ResolveMCPRequest
	(*ResolveMCPResponse)(nil),    // 13: orange.inspect.v1.ResolveMCPResponse
	(*MatchViewRequest)(nil),      // 14: orange.inspect.v1.MatchViewRequest
	(*PickViewRequest)(nil),       // 15: orange.inspect.v1.PickViewRequest
	(*AdaptViewRequest)(nil),      // 16: orange.inspect.v1.AdaptViewRequest
	(*MatchViewResponse)(nil),     // 17: orange.inspect.v1.MatchViewResponse
	(*PickViewResponse)(nil),      // 18: orange.inspect.v1.PickViewResponse
	(*AdaptViewResponse)(nil),     // 19: orange.inspect.v1.AdaptViewResponse
	(*GenerationInfo)(nil),        // 20: orange.inspect.v1.GenerationInfo
	(*ComponentInfo)(nil),         // 21: orange.inspect.v1.ComponentInfo
	(*ScopeInfo)(nil),             // 22: orange.inspect.v1.ScopeInfo
	(*ProviderInfo)(nil),          // 23: orange.inspect.v1.ProviderInfo
	(*ModelInfo)(nil),             // 24: orange.inspect.v1.ModelInfo
	(*LLMRoute)(nil),              // 25: orange.inspect.v1.LLMRoute
	(*MCPRoute)(nil),              // 26: orange.inspect.v1.MCPRoute
	(*MCPTool)(nil),               // 27: orange.inspect.v1.MCPTool
	nil,                           // 28: orange.inspect.v1.ProviderInfo.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 29: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 30: google.protobuf.Struct
}
var file_orange_inspect_v1_inspection_proto_depIdxs = []int32{
	20, // 0: orange.inspect.v1.StatusResponse.generation:type_name -> orange.inspect.v1.GenerationInfo
	29, // 1: orange.inspect.v1.StatusResponse.observed_at:type_name -> google.protobuf.Timestamp
	20, // 2: orange.inspect.v1.GenerationResponse.generation:type_name -> orange.inspect.v1.GenerationInfo
	20, // 3: orange.inspect.v1.ScopesResponse.generation:type_name -> orange.inspect.v1.GenerationInfo
	22, // 4: orange.inspect.v1.ScopesResponse.scopes:type_name -> orange.inspect.v1.ScopeInfo
	20, // 5: orange.inspect.v1.ProvidersResponse.generation:type_name -> orange.inspect.v1.GenerationInfo
	23, // 6: orange.inspect.v1.ProvidersResponse.providers:type_name -> orange.inspect.v1.ProviderInfo
	20, // 7: orange.inspect.v1.ModelsResponse.generation:type_name -> orange.inspect.v1.GenerationInfo
	24, // 8: orange.inspect.v1.ModelsResponse.models:type_name -> orange.inspect.v1.ModelInfo
	20, // 9: orange.inspect.v1.ResolveLLMResponse.generation:type_name -> orange.inspect.v1.GenerationInfo
	25, // 10: orange.inspect.v1.ResolveLLMResponse.route:type_name -> orange.inspect.v1.LLMRoute
	20, // 11: orange.inspect.v1.ResolveMCPResponse.generation:type_name -> orange.inspect.v1.GenerationInfo
	26, // 12: orange.inspect.v1.ResolveMCPResponse.route:type_name -> orange.inspect.v1.MCPRoute
	20, // 13: orange.inspect.v1.MatchViewResponse.generation:type_name -> orange.inspect.v1.GenerationInfo
	30, // 14: orange.inspect.v1.MatchViewResponse.view:type_name -> google.protobuf.Struct
	20, // 15: orange.inspect.v1.PickViewResponse.generation:type_name -> orange.inspect.v1.GenerationInfo
	30, // 16: orange.inspect.v1.PickViewResponse.view:type_name -> google.protobuf.Struct
	20, // 17: orange.inspect.v1.AdaptViewResponse.generation:type_name -> orange.inspect.v1.GenerationInfo
	30, // 18: orange.inspect.v1.AdaptViewResponse.view:type_name -> google.protobuf.Struct
	21, // 19: orange.inspect.v1.GenerationInfo.components:type_name -> orange.inspect.v1.ComponentInfo
	29, // 20: orange.inspect.v1.GenerationInfo.observed_at:type_name -> google.protobuf.Timestamp
	28, // 21: orange.inspect.v1.ProviderInfo.metadata:type_name -> orange.inspect.v1.ProviderInfo.MetadataEntry
	27, // 22: orange.inspect.v1.MCPRoute.tools:type_name -> orange.inspect.v1.MCPTool
	0,  // 23: orange.inspect.v1.InspectionService.Status:input_type -> orange.inspect.v1.StatusRequest
	2,  // 24: orange.inspect.v1.InspectionService.Generation:input_type -> orange.inspect.v1.GenerationRequest
	4,  // 25: orange.inspect.v1.InspectionService.Scopes:input_type -> orange.inspect.v1.ScopesRequest
	6,  // 26: orange.inspect.v1.InspectionService.Providers:input_type -> orange.inspect.v1.ProvidersRequest
	8,  // 27: orange.inspect.v1.InspectionService.Models:input_type -> orange.inspect.v1.ModelsRequest
	10, // 28: orange.inspect.v1.InspectionService.ResolveLLM:input_type -> orange.inspect.v1.ResolveLLMRequest
	12, // 29: orange.inspect.v1.InspectionService.ResolveMCP:input_type -> orange.inspect.v1.ResolveMCPRequest
	14, // 30: orange.inspect.v1.InspectionService.MatchView:input_type -> orange.inspect.v1.MatchViewRequest
	15, // 31: orange.inspect.v1.InspectionService.PickView:input_type -> orange.inspect.v1.PickViewRequest
	16, // 32: orange.inspect.v1.InspectionService.AdaptView:input_type -> orange.inspect.v1.AdaptViewRequest
	1,  // 33: orange.inspect.v1.InspectionService.Status:output_type -> orange.inspect.v1.StatusResponse
	3,  // 34: orange.inspect.v1.InspectionService.Generation:output_type -> orange.inspect.v1.GenerationResponse
	5,  // 35: orange.inspect.v1.InspectionService.Scopes:output_type -> orange.inspect.v1.ScopesResponse
	7,  // 36: orange.inspect.v1.InspectionService.Providers:output_type -> orange.inspect.v1.ProvidersResponse
	9,  // 37: orange.inspect.v1.InspectionService.Models:output_type -> orange.inspect.v1.ModelsResponse
	11, // 38: orange.inspect.v1.InspectionService.ResolveLLM:output_type -> orange.inspect.v1.ResolveLLMResponse
	13, // 39: orange.inspect.v1.InspectionService.ResolveMCP:output_type -> orange.inspect.v1.ResolveMCPResponse
	17, // 40: orange.inspect.v1.InspectionService.MatchView:output_type -> orange.inspect.v1.MatchViewResponse
	18, // 41: orange.inspect.v1.InspectionService.PickView:output_type -> orange.inspect.v1.PickViewResponse
	19, // 42: orange.inspect.v1.InspectionService.AdaptView:output_type -> orange.inspect.v1.AdaptViewResponse
	33, // [33:43] is the sub-list for method output_type
	23, // [23:33] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_orange_inspect_v1_inspection_proto_init() }
func file_orange_inspect_v1_inspection_proto_init() {
	if File_orange_inspect_v1_inspection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orange_inspect_v1_inspection_proto_rawDesc), len(file_orange_inspect_v1_inspection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orange_inspect_v1_inspection_proto_goTypes,
		DependencyIndexes: file_orange_inspect_v1_inspection_proto_depIdxs,
		MessageInfos:      file_orange_inspect_v1_inspection_proto_msgTypes,
	}.Build()
	File_orange_inspect_v1_inspection_proto = out.File
	file_orange_inspect_v1_inspection_proto_goTypes = nil
	file_orange_inspect_v1_inspection_proto_depIdxs = nil
}
