// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orange/config/v1/service.proto

package configv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/dio/orange/api/orange/auth/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FetchRequest is the unary cold-start or reconnect path. When both
// last_version and last_checksum still match the server's current snapshot,
// the server replies with Unchanged. Send last_version = 0 and omit
// last_checksum for an unconditional fetch.
type FetchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// last_version is the highest version the client has applied; 0 = unconditional.
	LastVersion uint64 `protobuf:"varint,2,opt,name=last_version,json=lastVersion,proto3" json:"last_version,omitempty"`
	// last_checksum is the SHA-256 of the last accepted decompressed payload.
	// When present it must be exactly 32 bytes. Omit (leave empty) for an
	// unconditional fetch or when last_version alone is sufficient.
	LastChecksum  []byte `protobuf:"bytes,3,opt,name=last_checksum,json=lastChecksum,proto3" json:"last_checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_orange_config_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetLastVersion() uint64 {
	if x != nil {
		return x.LastVersion
	}
	return 0
}

func (x *FetchRequest) GetLastChecksum() []byte {
	if x != nil {
		return x.LastChecksum
	}
	return nil
}

type FetchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*FetchResponse_Snapshot
	//	*FetchResponse_Unchanged
	Result        isFetchResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_orange_config_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetResult() isFetchResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FetchResponse) GetSnapshot() *SnapshotEnvelope {
	if x != nil {
		if x, ok := x.Result.(*FetchResponse_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *FetchResponse) GetUnchanged() *Unchanged {
	if x != nil {
		if x, ok := x.Result.(*FetchResponse_Unchanged); ok {
			return x.Unchanged
		}
	}
	return nil
}

type isFetchResponse_Result interface {
	isFetchResponse_Result()
}

type FetchResponse_Snapshot struct {
	Snapshot *SnapshotEnvelope `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"` // current snapshot (version or checksum changed)
}

type FetchResponse_Unchanged struct {
	Unchanged *Unchanged `protobuf:"bytes,2,opt,name=unchanged,proto3,oneof"` // version and checksum still match; no payload
}

func (*FetchResponse_Snapshot) isFetchResponse_Result() {}

func (*FetchResponse_Unchanged) isFetchResponse_Result() {}

// Unchanged is returned by Fetch when the client's snapshot is already current.
type Unchanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unchanged) Reset() {
	*x = Unchanged{}
	mi := &file_orange_config_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unchanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unchanged) ProtoMessage() {}

func (x *Unchanged) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unchanged.ProtoReflect.Descriptor instead.
func (*Unchanged) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_service_proto_rawDescGZIP(), []int{2}
}

var File_orange_config_v1_service_proto protoreflect.FileDescriptor

const file_orange_config_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1eorange/config/v1/service.proto\x12\x10orange.config.v1\x1a\x1bbuf/validate/validate.proto\x1a!orange/auth/v1/auth_options.proto\x1a\x1forange/config/v1/snapshot.proto\"\xde\x01\n" +
	"\fFetchRequest\x12!\n" +
	"\flast_version\x18\x02 \x01(\x04R\vlastVersion\x12\xaa\x01\n" +
	"\rlast_checksum\x18\x03 \x01(\fB\x84\x01\xbaH\x80\x01\xba\x01}\n" +
	"\x19fetch_checksum_sha256_len\x129last_checksum must be empty or exactly 32 bytes (SHA-256)\x1a%this.size() == 0 || this.size() == 32R\flastChecksum\"\x9f\x01\n" +
	"\rFetchResponse\x12@\n" +
	"\bsnapshot\x18\x01 \x01(\v2\".orange.config.v1.SnapshotEnvelopeH\x00R\bsnapshot\x12;\n" +
	"\tunchanged\x18\x02 \x01(\v2\x1b.orange.config.v1.UnchangedH\x00R\tunchangedB\x0f\n" +
	"\x06result\x12\x05\xbaH\x02\b\x01\"\v\n" +
	"\tUnchanged2d\n" +
	"\x0fSnapshotService\x12Q\n" +
	"\x05Fetch\x12\x1e.orange.config.v1.FetchRequest\x1a\x1f.orange.config.v1.FetchResponse\"\a\xea\xb5S\x03\n" +
	"\x01\x03B\xbb\x01\n" +
	"\x14com.orange.config.v1B\fServiceProtoP\x01Z3github.com/dio/orange/api/orange/config/v1;configv1\xa2\x02\x03OCX\xaa\x02\x10Orange.Config.V1\xca\x02\x10Orange\\Config\\V1\xe2\x02\x1cOrange\\Config\\V1\\GPBMetadata\xea\x02\x12Orange::Config::V1b\x06proto3"

var (
	file_orange_config_v1_service_proto_rawDescOnce sync.Once
	file_orange_config_v1_service_proto_rawDescData []byte
)

func file_orange_config_v1_service_proto_rawDescGZIP() []byte {
	file_orange_config_v1_service_proto_rawDescOnce.Do(func() {
		file_orange_config_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orange_config_v1_service_proto_rawDesc), len(file_orange_config_v1_service_proto_rawDesc)))
	})
	return file_orange_config_v1_service_proto_rawDescData
}

var file_orange_config_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_orange_config_v1_service_proto_goTypes = []any{
	(*FetchRequest)(nil),     // 0: orange.config.v1.FetchRequest
	(*FetchResponse)(nil),    // 1: orange.config.v1.FetchResponse
	(*Unchanged)(nil),        // 2: orange.config.v1.Unchanged
	(*SnapshotEnvelope)(nil), // 3: orange.config.v1.SnapshotEnvelope
}
var file_orange_config_v1_service_proto_depIdxs = []int32{
	3, // 0: orange.config.v1.FetchResponse.snapshot:type_name -> orange.config.v1.SnapshotEnvelope
	2, // 1: orange.config.v1.FetchResponse.unchanged:type_name -> orange.config.v1.Unchanged
	0, // 2: orange.config.v1.SnapshotService.Fetch:input_type -> orange.config.v1.FetchRequest
	1, // 3: orange.config.v1.SnapshotService.Fetch:output_type -> orange.config.v1.FetchResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_orange_config_v1_service_proto_init() }
func file_orange_config_v1_service_proto_init() {
	if File_orange_config_v1_service_proto != nil {
		return
	}
	file_orange_config_v1_snapshot_proto_init()
	file_orange_config_v1_service_proto_msgTypes[1].OneofWrappers = []any{
		(*FetchResponse_Snapshot)(nil),
		(*FetchResponse_Unchanged)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orange_config_v1_service_proto_rawDesc), len(file_orange_config_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orange_config_v1_service_proto_goTypes,
		DependencyIndexes: file_orange_config_v1_service_proto_depIdxs,
		MessageInfos:      file_orange_config_v1_service_proto_msgTypes,
	}.Build()
	File_orange_config_v1_service_proto = out.File
	file_orange_config_v1_service_proto_goTypes = nil
	file_orange_config_v1_service_proto_depIdxs = nil
}
