// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orange/config/v1/snapshot.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SnapshotEnvelope is the outermost frame delivered over gRPC or HTTP.
// Payload contains a compressed (or raw) ConfigPayload proto.
type SnapshotEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`  // monotonically increasing; receiver discards if <= last accepted
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`   // compressed ConfigPayload proto bytes
	Checksum      []byte                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"` // SHA-256 of the decompressed payload bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEnvelope) Reset() {
	*x = SnapshotEnvelope{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEnvelope) ProtoMessage() {}

func (x *SnapshotEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEnvelope.ProtoReflect.Descriptor instead.
func (*SnapshotEnvelope) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotEnvelope) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SnapshotEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SnapshotEnvelope) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

var File_orange_config_v1_snapshot_proto protoreflect.FileDescriptor

const file_orange_config_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1forange/config/v1/snapshot.proto\x12\x10orange.config.v1\"b\n" +
	"\x10SnapshotEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\fR\bchecksumB\xbc\x01\n" +
	"\x14com.orange.config.v1B\rSnapshotProtoP\x01Z3github.com/dio/orange/api/orange/config/v1;configv1\xa2\x02\x03OCX\xaa\x02\x10Orange.Config.V1\xca\x02\x10Orange\\Config\\V1\xe2\x02\x1cOrange\\Config\\V1\\GPBMetadata\xea\x02\x12Orange::Config::V1b\x06proto3"

var (
	file_orange_config_v1_snapshot_proto_rawDescOnce sync.Once
	file_orange_config_v1_snapshot_proto_rawDescData []byte
)

func file_orange_config_v1_snapshot_proto_rawDescGZIP() []byte {
	file_orange_config_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_orange_config_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orange_config_v1_snapshot_proto_rawDesc), len(file_orange_config_v1_snapshot_proto_rawDesc)))
	})
	return file_orange_config_v1_snapshot_proto_rawDescData
}

var file_orange_config_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_orange_config_v1_snapshot_proto_goTypes = []any{
	(*SnapshotEnvelope)(nil), // 0: orange.config.v1.SnapshotEnvelope
}
var file_orange_config_v1_snapshot_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orange_config_v1_snapshot_proto_init() }
func file_orange_config_v1_snapshot_proto_init() {
	if File_orange_config_v1_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orange_config_v1_snapshot_proto_rawDesc), len(file_orange_config_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orange_config_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_orange_config_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_orange_config_v1_snapshot_proto_msgTypes,
	}.Build()
	File_orange_config_v1_snapshot_proto = out.File
	file_orange_config_v1_snapshot_proto_goTypes = nil
	file_orange_config_v1_snapshot_proto_depIdxs = nil
}
