// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orange/config/v1/snapshot.proto

package configv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SnapshotEnvelope is the outermost frame delivered over gRPC or HTTP.
// Payload contains a compressed (or raw) ConfigPayload proto bytes.
type SnapshotEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`  // monotonically increasing; receiver discards if <= last accepted
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`   // compressed ConfigPayload proto bytes
	Checksum      []byte                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"` // SHA-256 of the decompressed payload bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEnvelope) Reset() {
	*x = SnapshotEnvelope{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEnvelope) ProtoMessage() {}

func (x *SnapshotEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEnvelope.ProtoReflect.Descriptor instead.
func (*SnapshotEnvelope) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotEnvelope) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SnapshotEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SnapshotEnvelope) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

// ConfigPayload is the typed wrapper for bundle bytes and their metadata.
// Stored as the payload field of SnapshotEnvelope (optionally compressed).
type ConfigPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Format        *PayloadFormat         `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      *SnapshotMetadata      `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPayload) Reset() {
	*x = ConfigPayload{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPayload) ProtoMessage() {}

func (x *ConfigPayload) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPayload.ProtoReflect.Descriptor instead.
func (*ConfigPayload) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigPayload) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ConfigPayload) GetFormat() *PayloadFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *ConfigPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConfigPayload) GetMetadata() *SnapshotMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PayloadFormat describes the encoding of the bundle bytes in ConfigPayload.payload.
type PayloadFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Encoding      string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"`
	FormatVersion string                 `protobuf:"bytes,3,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadFormat) Reset() {
	*x = PayloadFormat{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadFormat) ProtoMessage() {}

func (x *PayloadFormat) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadFormat.ProtoReflect.Descriptor instead.
func (*PayloadFormat) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *PayloadFormat) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *PayloadFormat) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *PayloadFormat) GetFormatVersion() string {
	if x != nil {
		return x.FormatVersion
	}
	return ""
}

// SnapshotMetadata carries diagnostic and routing information for a snapshot.
// Fields are opaque labels; no secret values, tenant keys, or user identifiers.
type SnapshotMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Producer       string                 `protobuf:"bytes,1,opt,name=producer,proto3" json:"producer,omitempty"`
	SourceRevision string                 `protobuf:"bytes,2,opt,name=source_revision,json=sourceRevision,proto3" json:"source_revision,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Lane           string                 `protobuf:"bytes,4,opt,name=lane,proto3" json:"lane,omitempty"`
	ScopeKind      string                 `protobuf:"bytes,5,opt,name=scope_kind,json=scopeKind,proto3" json:"scope_kind,omitempty"`
	ScopeId        string                 `protobuf:"bytes,6,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	Scopes         []string               `protobuf:"bytes,7,rep,name=scopes,proto3" json:"scopes,omitempty"`
	PayloadSize    uint64                 `protobuf:"varint,8,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	PayloadSha256  []byte                 `protobuf:"bytes,9,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SnapshotMetadata) Reset() {
	*x = SnapshotMetadata{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMetadata) ProtoMessage() {}

func (x *SnapshotMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMetadata.ProtoReflect.Descriptor instead.
func (*SnapshotMetadata) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotMetadata) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *SnapshotMetadata) GetSourceRevision() string {
	if x != nil {
		return x.SourceRevision
	}
	return ""
}

func (x *SnapshotMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SnapshotMetadata) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

func (x *SnapshotMetadata) GetScopeKind() string {
	if x != nil {
		return x.ScopeKind
	}
	return ""
}

func (x *SnapshotMetadata) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *SnapshotMetadata) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *SnapshotMetadata) GetPayloadSize() uint64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *SnapshotMetadata) GetPayloadSha256() []byte {
	if x != nil {
		return x.PayloadSha256
	}
	return nil
}

// MappedSplitSnapshot is the typed SoTW map for Cherry mapped-split delivery.
// Component bundle bytes are still fetched as ConfigPayload snapshots through
// SnapshotService.FetchMappedSplitBundle using the resource named by each
// bundle ref.
type MappedSplitSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // monotonically increasing map version
	Checksum      []byte                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Map           *MappedSplitMap        `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappedSplitSnapshot) Reset() {
	*x = MappedSplitSnapshot{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappedSplitSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedSplitSnapshot) ProtoMessage() {}

func (x *MappedSplitSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedSplitSnapshot.ProtoReflect.Descriptor instead.
func (*MappedSplitSnapshot) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *MappedSplitSnapshot) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MappedSplitSnapshot) GetChecksum() []byte {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *MappedSplitSnapshot) GetMap() *MappedSplitMap {
	if x != nil {
		return x.Map
	}
	return nil
}

// MappedSplitMap describes every current component bundle for one authenticated
// lane. It is SoTW: omitted component refs are removed from the active view.
type MappedSplitMap struct {
	state                   protoimpl.MessageState                     `protogen:"open.v1"`
	FormatVersion           string                                     `protobuf:"bytes,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	ScopeKind               string                                     `protobuf:"bytes,2,opt,name=scope_kind,json=scopeKind,proto3" json:"scope_kind,omitempty"`
	ScopeId                 string                                     `protobuf:"bytes,3,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	Scopes                  []string                                   `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	GenerationId            string                                     `protobuf:"bytes,5,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	MapRevision             uint64                                     `protobuf:"varint,6,opt,name=map_revision,json=mapRevision,proto3" json:"map_revision,omitempty"`
	LlmDefaultPrincipalSlug string                                     `protobuf:"bytes,7,opt,name=llm_default_principal_slug,json=llmDefaultPrincipalSlug,proto3" json:"llm_default_principal_slug,omitempty"`
	Partitioning            map[string]*MappedSplitPartitionSpec       `protobuf:"bytes,8,rep,name=partitioning,proto3" json:"partitioning,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Bundles                 map[string]*MappedSplitBundleRef           `protobuf:"bytes,9,rep,name=bundles,proto3" json:"bundles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PartitionBundles        map[string]*MappedSplitPartitionBundleRefs `protobuf:"bytes,10,rep,name=partition_bundles,json=partitionBundles,proto3" json:"partition_bundles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MappedSplitMap) Reset() {
	*x = MappedSplitMap{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappedSplitMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedSplitMap) ProtoMessage() {}

func (x *MappedSplitMap) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedSplitMap.ProtoReflect.Descriptor instead.
func (*MappedSplitMap) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *MappedSplitMap) GetFormatVersion() string {
	if x != nil {
		return x.FormatVersion
	}
	return ""
}

func (x *MappedSplitMap) GetScopeKind() string {
	if x != nil {
		return x.ScopeKind
	}
	return ""
}

func (x *MappedSplitMap) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *MappedSplitMap) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *MappedSplitMap) GetGenerationId() string {
	if x != nil {
		return x.GenerationId
	}
	return ""
}

func (x *MappedSplitMap) GetMapRevision() uint64 {
	if x != nil {
		return x.MapRevision
	}
	return 0
}

func (x *MappedSplitMap) GetLlmDefaultPrincipalSlug() string {
	if x != nil {
		return x.LlmDefaultPrincipalSlug
	}
	return ""
}

func (x *MappedSplitMap) GetPartitioning() map[string]*MappedSplitPartitionSpec {
	if x != nil {
		return x.Partitioning
	}
	return nil
}

func (x *MappedSplitMap) GetBundles() map[string]*MappedSplitBundleRef {
	if x != nil {
		return x.Bundles
	}
	return nil
}

func (x *MappedSplitMap) GetPartitionBundles() map[string]*MappedSplitPartitionBundleRefs {
	if x != nil {
		return x.PartitionBundles
	}
	return nil
}

// MappedSplitPartitionSpec describes deterministic cohorting for a partitioned lane.
type MappedSplitPartitionSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Partitions    uint32                 `protobuf:"varint,3,opt,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappedSplitPartitionSpec) Reset() {
	*x = MappedSplitPartitionSpec{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappedSplitPartitionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedSplitPartitionSpec) ProtoMessage() {}

func (x *MappedSplitPartitionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedSplitPartitionSpec.ProtoReflect.Descriptor instead.
func (*MappedSplitPartitionSpec) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{6}
}

func (x *MappedSplitPartitionSpec) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *MappedSplitPartitionSpec) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MappedSplitPartitionSpec) GetPartitions() uint32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

// MappedSplitBundleRef identifies one component bundle resource.
type MappedSplitBundleRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Component     string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Checksum      uint64                 `protobuf:"varint,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size          uint64                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappedSplitBundleRef) Reset() {
	*x = MappedSplitBundleRef{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappedSplitBundleRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedSplitBundleRef) ProtoMessage() {}

func (x *MappedSplitBundleRef) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedSplitBundleRef.ProtoReflect.Descriptor instead.
func (*MappedSplitBundleRef) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{7}
}

func (x *MappedSplitBundleRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MappedSplitBundleRef) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *MappedSplitBundleRef) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *MappedSplitBundleRef) GetChecksum() uint64 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *MappedSplitBundleRef) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// MappedSplitPartitionBundleRef identifies one partitioned component bundle.
type MappedSplitPartitionBundleRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     uint32                 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Ref           *MappedSplitBundleRef  `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappedSplitPartitionBundleRef) Reset() {
	*x = MappedSplitPartitionBundleRef{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappedSplitPartitionBundleRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedSplitPartitionBundleRef) ProtoMessage() {}

func (x *MappedSplitPartitionBundleRef) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedSplitPartitionBundleRef.ProtoReflect.Descriptor instead.
func (*MappedSplitPartitionBundleRef) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{8}
}

func (x *MappedSplitPartitionBundleRef) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *MappedSplitPartitionBundleRef) GetRef() *MappedSplitBundleRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

// MappedSplitPartitionBundleRefs wraps repeated refs because proto maps cannot
// use repeated fields as map values.
type MappedSplitPartitionBundleRefs struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Refs          []*MappedSplitPartitionBundleRef `protobuf:"bytes,1,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappedSplitPartitionBundleRefs) Reset() {
	*x = MappedSplitPartitionBundleRefs{}
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappedSplitPartitionBundleRefs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappedSplitPartitionBundleRefs) ProtoMessage() {}

func (x *MappedSplitPartitionBundleRefs) ProtoReflect() protoreflect.Message {
	mi := &file_orange_config_v1_snapshot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappedSplitPartitionBundleRefs.ProtoReflect.Descriptor instead.
func (*MappedSplitPartitionBundleRefs) Descriptor() ([]byte, []int) {
	return file_orange_config_v1_snapshot_proto_rawDescGZIP(), []int{9}
}

func (x *MappedSplitPartitionBundleRefs) GetRefs() []*MappedSplitPartitionBundleRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

var File_orange_config_v1_snapshot_proto protoreflect.FileDescriptor

const file_orange_config_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1forange/config/v1/snapshot.proto\x12\x10orange.config.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\x10SnapshotEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\fR\bchecksum\"\xdb\x01\n" +
	"\rConfigPayload\x12.\n" +
	"\x0eschema_version\x18\x01 \x01(\rB\a\xbaH\x04*\x02 \x00R\rschemaVersion\x127\n" +
	"\x06format\x18\x02 \x01(\v2\x1f.orange.config.v1.PayloadFormatR\x06format\x12!\n" +
	"\apayload\x18\x03 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\apayload\x12>\n" +
	"\bmetadata\x18\x04 \x01(\v2\".orange.config.v1.SnapshotMetadataR\bmetadata\"\x83\x01\n" +
	"\rPayloadFormat\x12&\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tmediaType\x12#\n" +
	"\bencoding\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bencoding\x12%\n" +
	"\x0eformat_version\x18\x03 \x01(\tR\rformatVersion\"\xc3\x03\n" +
	"\x10SnapshotMetadata\x12\x1a\n" +
	"\bproducer\x18\x01 \x01(\tR\bproducer\x12'\n" +
	"\x0fsource_revision\x18\x02 \x01(\tR\x0esourceRevision\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04lane\x18\x04 \x01(\tR\x04lane\x12\x1d\n" +
	"\n" +
	"scope_kind\x18\x05 \x01(\tR\tscopeKind\x12\x19\n" +
	"\bscope_id\x18\x06 \x01(\tR\ascopeId\x12\x16\n" +
	"\x06scopes\x18\a \x03(\tR\x06scopes\x12!\n" +
	"\fpayload_size\x18\b \x01(\x04R\vpayloadSize\x12\xa5\x01\n" +
	"\x0epayload_sha256\x18\t \x01(\fB~\xbaH{\xba\x01x\n" +
	"\x13metadata_sha256_len\x12:payload_sha256 must be empty or exactly 32 bytes (SHA-256)\x1a%this.size() == 0 || this.size() == 32R\rpayloadSha256\"\xea\x01\n" +
	"\x13MappedSplitSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x84\x01\n" +
	"\bchecksum\x18\x02 \x01(\fBh\xbaHe\xba\x01b\n" +
	" mapped_split_checksum_sha256_len\x12+checksum must be exactly 32 bytes (SHA-256)\x1a\x11this.size() == 32R\bchecksum\x122\n" +
	"\x03map\x18\x03 \x01(\v2 .orange.config.v1.MappedSplitMapR\x03map\"\xdc\x06\n" +
	"\x0eMappedSplitMap\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\tR\rformatVersion\x12\x1d\n" +
	"\n" +
	"scope_kind\x18\x02 \x01(\tR\tscopeKind\x12\x19\n" +
	"\bscope_id\x18\x03 \x01(\tR\ascopeId\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12#\n" +
	"\rgeneration_id\x18\x05 \x01(\tR\fgenerationId\x12!\n" +
	"\fmap_revision\x18\x06 \x01(\x04R\vmapRevision\x12;\n" +
	"\x1allm_default_principal_slug\x18\a \x01(\tR\x17llmDefaultPrincipalSlug\x12V\n" +
	"\fpartitioning\x18\b \x03(\v22.orange.config.v1.MappedSplitMap.PartitioningEntryR\fpartitioning\x12G\n" +
	"\abundles\x18\t \x03(\v2-.orange.config.v1.MappedSplitMap.BundlesEntryR\abundles\x12c\n" +
	"\x11partition_bundles\x18\n" +
	" \x03(\v26.orange.config.v1.MappedSplitMap.PartitionBundlesEntryR\x10partitionBundles\x1ak\n" +
	"\x11PartitioningEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.orange.config.v1.MappedSplitPartitionSpecR\x05value:\x028\x01\x1ab\n" +
	"\fBundlesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.orange.config.v1.MappedSplitBundleRefR\x05value:\x028\x01\x1au\n" +
	"\x15PartitionBundlesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12F\n" +
	"\x05value\x18\x02 \x01(\v20.orange.config.v1.MappedSplitPartitionBundleRefsR\x05value:\x028\x01\"j\n" +
	"\x18MappedSplitPartitionSpec\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1e\n" +
	"\n" +
	"partitions\x18\x03 \x01(\rR\n" +
	"partitions\"\x90\x01\n" +
	"\x14MappedSplitBundleRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\x04R\bchecksum\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\"w\n" +
	"\x1dMappedSplitPartitionBundleRef\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\rR\tpartition\x128\n" +
	"\x03ref\x18\x02 \x01(\v2&.orange.config.v1.MappedSplitBundleRefR\x03ref\"e\n" +
	"\x1eMappedSplitPartitionBundleRefs\x12C\n" +
	"\x04refs\x18\x01 \x03(\v2/.orange.config.v1.MappedSplitPartitionBundleRefR\x04refsB\xbc\x01\n" +
	"\x14com.orange.config.v1B\rSnapshotProtoP\x01Z3github.com/dio/orange/api/orange/config/v1;configv1\xa2\x02\x03OCX\xaa\x02\x10Orange.Config.V1\xca\x02\x10Orange\\Config\\V1\xe2\x02\x1cOrange\\Config\\V1\\GPBMetadata\xea\x02\x12Orange::Config::V1b\x06proto3"

var (
	file_orange_config_v1_snapshot_proto_rawDescOnce sync.Once
	file_orange_config_v1_snapshot_proto_rawDescData []byte
)

func file_orange_config_v1_snapshot_proto_rawDescGZIP() []byte {
	file_orange_config_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_orange_config_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orange_config_v1_snapshot_proto_rawDesc), len(file_orange_config_v1_snapshot_proto_rawDesc)))
	})
	return file_orange_config_v1_snapshot_proto_rawDescData
}

var file_orange_config_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_orange_config_v1_snapshot_proto_goTypes = []any{
	(*SnapshotEnvelope)(nil),               // 0: orange.config.v1.SnapshotEnvelope
	(*ConfigPayload)(nil),                  // 1: orange.config.v1.ConfigPayload
	(*PayloadFormat)(nil),                  // 2: orange.config.v1.PayloadFormat
	(*SnapshotMetadata)(nil),               // 3: orange.config.v1.SnapshotMetadata
	(*MappedSplitSnapshot)(nil),            // 4: orange.config.v1.MappedSplitSnapshot
	(*MappedSplitMap)(nil),                 // 5: orange.config.v1.MappedSplitMap
	(*MappedSplitPartitionSpec)(nil),       // 6: orange.config.v1.MappedSplitPartitionSpec
	(*MappedSplitBundleRef)(nil),           // 7: orange.config.v1.MappedSplitBundleRef
	(*MappedSplitPartitionBundleRef)(nil),  // 8: orange.config.v1.MappedSplitPartitionBundleRef
	(*MappedSplitPartitionBundleRefs)(nil), // 9: orange.config.v1.MappedSplitPartitionBundleRefs
	nil,                                    // 10: orange.config.v1.MappedSplitMap.PartitioningEntry
	nil,                                    // 11: orange.config.v1.MappedSplitMap.BundlesEntry
	nil,                                    // 12: orange.config.v1.MappedSplitMap.PartitionBundlesEntry
	(*timestamppb.Timestamp)(nil),          // 13: google.protobuf.Timestamp
}
var file_orange_config_v1_snapshot_proto_depIdxs = []int32{
	2,  // 0: orange.config.v1.ConfigPayload.format:type_name -> orange.config.v1.PayloadFormat
	3,  // 1: orange.config.v1.ConfigPayload.metadata:type_name -> orange.config.v1.SnapshotMetadata
	13, // 2: orange.config.v1.SnapshotMetadata.created_at:type_name -> google.protobuf.Timestamp
	5,  // 3: orange.config.v1.MappedSplitSnapshot.map:type_name -> orange.config.v1.MappedSplitMap
	10, // 4: orange.config.v1.MappedSplitMap.partitioning:type_name -> orange.config.v1.MappedSplitMap.PartitioningEntry
	11, // 5: orange.config.v1.MappedSplitMap.bundles:type_name -> orange.config.v1.MappedSplitMap.BundlesEntry
	12, // 6: orange.config.v1.MappedSplitMap.partition_bundles:type_name -> orange.config.v1.MappedSplitMap.PartitionBundlesEntry
	7,  // 7: orange.config.v1.MappedSplitPartitionBundleRef.ref:type_name -> orange.config.v1.MappedSplitBundleRef
	8,  // 8: orange.config.v1.MappedSplitPartitionBundleRefs.refs:type_name -> orange.config.v1.MappedSplitPartitionBundleRef
	6,  // 9: orange.config.v1.MappedSplitMap.PartitioningEntry.value:type_name -> orange.config.v1.MappedSplitPartitionSpec
	7,  // 10: orange.config.v1.MappedSplitMap.BundlesEntry.value:type_name -> orange.config.v1.MappedSplitBundleRef
	9,  // 11: orange.config.v1.MappedSplitMap.PartitionBundlesEntry.value:type_name -> orange.config.v1.MappedSplitPartitionBundleRefs
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_orange_config_v1_snapshot_proto_init() }
func file_orange_config_v1_snapshot_proto_init() {
	if File_orange_config_v1_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orange_config_v1_snapshot_proto_rawDesc), len(file_orange_config_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orange_config_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_orange_config_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_orange_config_v1_snapshot_proto_msgTypes,
	}.Build()
	File_orange_config_v1_snapshot_proto = out.File
	file_orange_config_v1_snapshot_proto_goTypes = nil
	file_orange_config_v1_snapshot_proto_depIdxs = nil
}
